from selenium import webdriver
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()
driver.implicitly_wait(10)
driver.get("https://practice.automationtesting.in/")
account = driver.find_element_by_id("menu-item-50")
account.click()
email = driver.find_element_by_id("reg_email")
email.send_keys('seventhsky1@rambler.ru')
password = driver.find_element_by_id("reg_password")
password.send_keys('Pasha1122!')
register = driver.find_element_by_name("register")
register.click()
driver.quit()

from selenium import webdriver
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()
driver.implicitly_wait(10)
driver.get("https://practice.automationtesting.in/")
account = driver.find_element_by_id("menu-item-50")
account.click()
login = driver.find_element_by_id("username")
login.send_keys('seventhsky1@rambler.ru')
passwordReg = driver.find_element_by_id("password")
passwordReg.send_keys('Pasha1122!')
login = driver.find_element_by_name("login")
login.click()
driver.quit()