from selenium import webdriver
import time
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()
driver.implicitly_wait(10)
driver.get("https://practice.automationtesting.in/")
shop = driver.find_element_by_id("menu-item-40")
shop.click()
time.sleep(5)
driver.execute_script("window.scrollBy(0, 300);")
add = driver.find_element_by_css_selector('[data-product_id="182"]')
add.click()
time.sleep(5)
add1 = driver.find_element_by_css_selector('[data-product_id="180"]')
add1.click()
time.sleep(5)
bucket = driver.find_element_by_class_name("wpmenucart-icon-shopping-cart-0")
bucket.click()
time.sleep(5)
remove = driver.find_element_by_css_selector(".cart_item:nth-child(1)>.product-remove>a")
remove.click()
time.sleep(5)
undo = driver.find_element_by_partial_link_text("Undo?")
undo.click()
quant = driver.find_element_by_css_selector("tbody:nth-child(2) input")
quant.clear()
quant.send_keys('3')
update = driver.find_element_by_name("update_cart")
update.click()
quant = driver.find_element_by_css_selector("tbody:nth-child(2) input")
kol=quant.get_attribute('value')
assert kol == "3"
time.sleep(5)
apply = driver.find_element_by_css_selector('[value="Apply Coupon"]')
apply.click()
code = driver.find_element_by_class_name('woocommerce-error')
assert str(code.text) == "Please enter a coupon code."